baseURL: "https://rafaeldefazio.com/"
languageCode: "en-us"
title: "Rafael de Fazio"
theme: "PaperMod"
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
    
menu:
  main:
  - identifier: home
    name: Home
    url: /
  - identifier: posts
    name: Posts
    url: /posts/
  - identifier: contact
    name: Contact
    url: /contact/

params:
  author: "Rafael de Fazio"
  description: "Senior Data Engineer with over 5 years of experience in delivering cloud-based data solutions."
  keywords:
    - Data Engineer
    - Python
    - SQL
    - ETL
    - Cloud
    - Big Data
    - Machine Learning
    - CI/CD
    - DevOps
  colorPalette: "light"

  menu:
    main:
      - name: "Home"
        url: "/"
        weight: 1
      - name: "Blog"
        url: "/blog/"
        weight: 2
      - name: "Contact"
        url: "/contact/"
        weight: 3

  social:
    linkedin: "https://linkedin.com/in/rafaelbdefazio"
    email: "rafaelbdefazio@gmail.com"
    github: "https://github.com/yourgithubusername"

  home:
    showInfo: true
    showResume: true
    showBlog: true
